baseURL = "https://www.osrtos.com/"
languageCode = "en-us"
title = "OSRTOS"
theme = "blowfish"

googleAnalytics = "UA-46054378-1"

[taxonomies]


[params]
  mainSections = ["rtos"]
  favicon = "favicon.ico"
  env= "production"
  [params.article]
    showDate = false

[menu]

  [[menu.main]]
    identifier = "rtos"
    name = "RTOS"
    url = "/"
    weight = -110

  [[menu.main]]
    identifier = "library"
    name = "Library"
    url = "/library/"
    weight = -100
